services:
  flask:
    build: ./flask
    container_name: flask-container
    restart: always
    ports:
      - "5000:5000" # Internal mapping (not exposed externally)
    env_file:
      - .env
    networks:
      - app-network
    
  nginx:
    build: ./nginx
    container_name: nginx-container
    restart: always
    ports:
      - "80:80" # Exposed externally
    depends_on:
      - flask
    networks:
      - app-network

networks:
  app-network:
    driver: bridge