# Use the official Nginx image
FROM nginx:latest

# Copy the custon Nginx config
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80 for web traffic
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
